### ISSUE TITLE
Notify the patterns to validate the metrics.

### ISSUE THREAD

**Issue by tsevillano** [chonton/dogstatd-client#1]
When I'm using this library, I don't find the pattern to validate the metrics parameters. (On the Readme.)

If you like, I can take my time to add it!.

**Comment by chonton** [comment]
I've updated and published the [javadocs](https://chonton.github.io/dogstatd-client/0.0.2/apidocs).  Does this solve your issue?

**Comment by tsevillano** [comment]
thanks!
