### ISSUE TITLE
Missing information in JAVADOC.

### ISSUE THREAD

**Issue by tsevillano** [chonton/dogstatd-client#2]
I analysed your code and I saw you missing to put the parameter `throttleInterval` in the javadoc...

Can you add please? Has datadog some restriction to send more than 1 message per minute?

I tried to found this information in the datadog documentation but I didn't found. 

https://github.com/chonton/dogstatd-client/blob/7b6a701abf365cd350d8a7714c0b38a2f1d875dd/src/main/java/org/honton/chas/dogstatd/model/Sender.java#L81

**Comment by chonton** [comment]
[Sender Javadoc updated](https://chonton.github.io/dogstatd-client/0.0.2/apidocs/index.html?org/honton/chas/dogstatd/model/Sender.html)
